version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
        - action: rebuild
          path: ./server/package.json
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:admin@db:5432/fyd_app
      - CLIENT_URL=http://localhost:5173
      - PORT=3000
      - AWS_API_URL=${AWS_API_URL}
      - AWS_API_TOKEN=${AWS_API_TOKEN}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - TICKETMASTER_API_KEY=${TICKETMASTER_API_KEY}

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fyd_app

volumes:
  postgres_data:
